### ISSUE TITLE
Seeon and Veetle must be play by dvd

### ISSUE THREAD

**Issue by Goofkilla** [t0mm0/t0mm0-xbmc-plugins#7]
I use those plugins on my xbox (Revision: 30961)everyday they are really awesome thank a lot for  creating them.But to play a stream you must do play with...  and select dvd . Could you add a setting function or set those plugins to play automatically with the dvd.I know nothing about coding i've try reading your SimpleXBMCAddonTutorial but my brain melted.Once again thank you for your  plugins .
Sorry me English very bad :(

**Comment by t0mm0** [comment]
hi,

yes i notice this problem too. unfortunately xbmc doesn't appear to provide a way to specify the player when you need to resolve the url at play time. i have asked on the xbmc forums and others have said it would be useful too but nobody came up with a way of doing it.

i just make dvdplayer the default player on xbox which is fine for my purposes, but you can also add a playercorefactory.xml setting if you want finer control (search the forum for info).

t0mm0
